### ISSUE TITLE
Question about the User Model

### ISSUE THREAD

**Issue by VictorQRS** [Superformula/cloud-backend-test#1]
The (User Model)[https://github.com/Superformula/cloud-backend-test#backend-context] in the README.md is a model for the GraphQL API or for the database?

Another question is: can I extend functionality of this model (add another field, for example)?

**Comment by pedro-sf** [comment]
Hi Victor!

That model is a rough sketch of the information we want. Feel free to model your contract or database however you wish. Whatever your pick is, just make sure that it meets all of the requirements outlined in the test, and you should be good :)
