### ISSUE TITLE
Functionality: Fetch geolocation

### ISSUE THREAD

**Issue by fabiocmarques** [Superformula/cloud-backend-test#2]
Hello!

I would like to know more about the fetch geolocation feature, could I have some use examples? Is there anything required other than latitude and longitude? How is this information related to the User? Is it just a front-end free query? I understood that the "address" field would be some string user input and geolocation is not directly related to it, am I wrong?

I'm using Mapbox library, but its usage is mainly with integrated front-end maps, so I'm trying to understand what fields matter most.

(By the way, at least for me, the NASA link on README.md is broken)

**Comment by pedro-sf** [comment]
Hi @fabiocmarques!

I will do my best to clarify the questions. 😄 

> I would like to know more about the fetch geolocation feature, could I have some use examples? Is there anything required other than latitude and longitude?

It's part of the test to figure out which properties should be used to meet all requirements of your consumer and your API. **As long as you meet all functional requirements of the APIs and your hypothetical consumer's requirements,** you should be good. 


> I understood that the "address" field would be some string user input and geolocation is not directly related to it, am I wrong?

It depends on your architecture. For those decisions, remember to anchor yourself on the API's requirements and the consumer's requirements. In the end, your architecture must deliver the functionality requested by the hypothetical front-end team while also providing all the required services in the backend. 

There is no hard structure for the address field in your database model. That pick is up to you. 😄
